apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: deny0fe3d-python-gitops
  description: This is GitOps manifest for deny0fe3d-python   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: rhtap/gitops=deny0fe3d-python
    backstage.io/kubernetes-id: deny0fe3d-python 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: deny0fe3d-python   
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:deny0fe3d-python
